### ISSUE TITLE
Failed to call service : turn on: Unknown error

### ISSUE THREAD

**Issue by salehdelaval** [bmccluskey/robovac#4]
Hi, 
thank you so much for this integration.

i added through HACS to my HASSIO (running on VM) and the integration added successfully, my two G30 robovac found on integration and i added the IP addresses obtained from my modem (double checked), but when i start the Robovac from Home assistant it returns the following error:
**Failed to call service vacuum.turn_on. unknown error.**
this happens on both robovacs.
any solutions will be appreciated.

**Comment by HumanSkunk** [comment]
If you use the service Vacuum: start/pause you can start it that way. That is what I am doing. This the same behaviour as the issue I raised # #3

**Comment by Everett115** [comment]
You can create a script like the ones in the read me that changes the mode. This will start the vacuum in the mode that your script calls for
Here is an example:
```
30c_autoclean:
  alias: 30C_autoClean
  sequence:
  - service: vacuum.send_command
    data:
      command: autoClean
    target:
      entity_id: vacuum.suc_boi
  mode: single
```
The command call also be changed based on what mode you want. My 30C Max supports these four, autoClean edgeClean smallRoomClean spotClean.

If you are using a the xiaomi custom vacuum card you can modify the service that is called for any of the buttons to be a script. In the following example the start button is disabled, the paused button is modified, and a new button for auto clean mode is created. You could also change the start button to call the auto cleaning script.
```
buttons:
  start: false
  pause:
    service: vacuum.start_pause
    label: Start/ Pause
    icon: mdi:play-pause
  auto:
    icon: mdi:refresh-auto
    label: Auto Clean
    service: script.30c_autoclean
```
Here is a picture of my card that adds buttons for all of the cleaning mode scripts. 

![Screenshot_20221206-115714](https://user-images.githubusercontent.com/57685216/205986586-f738c9f9-0d7e-4f2a-8541-4d6509c591f1.png)
